language: python
python:
- '3.6'
install: pip install -r deadline_bot/requirements.txt
script: py.test
before_install:
- openssl aes-256-cbc -K $encrypted_5ba21af0aaba_key -iv $encrypted_5ba21af0aaba_iv
  -in deadline_bot/.env.enc -out deadline_bot/.env -d
- openssl aes-256-cbc -K $encrypted_5ba21af0aaba_key -iv $encrypted_5ba21af0aaba_iv
  -in deadline_bot/google_api_credential.json.enc -out deadline_bot/google_api_credential.json
  -d
