language: python
python:
- '3.6'
install: pip install -r deadline_bot/requirements.txt
script: py.test
before_install:
- openssl aes-256-cbc -K $encrypted_e23337679bfd_key -iv $encrypted_e23337679bfd_iv
  -in google_api_credential.json.enc -out deadline_bot/google_api_credential.json
  -d
- openssl aes-256-cbc -K $encrypted_e23337679bfd_key -iv $encrypted_e23337679bfd_iv
  -in .env.enc -out deadline_bot/.env -d
